### PR TITLE
Update docs website

### PR DESCRIPTION
**Pull request by pawelprazak**
A small website update inspired by #295

### CODE REVIEW

**Review by lbialy — CHANGES_REQUESTED** [review]
I'd hold my horses with this and implement extension methods for `Output[Resource]` before, it's few lines of code but will require changes here.

**Comment by pawelprazak** [comment]
> I'd hold my horses with this and implement extension methods for `Output[Resource]` before, it's few lines of code but will require changes here.

On the other hand, we'll have to update the docs, after the release, in a lots of places anyway, so we can do it incrementally.

**Comment by pawelprazak** [comment]
blocked on @lbialy

**Comment by lbialy** [comment]
ok I guess

**Review by lbialy — APPROVED** [review]

**Pull request merged**
