### PR TITLE
Regression test for #148

### PR DESCRIPTION
**Pull request by pawelprazak**
- add unit test
- improve error message

### CODE REVIEW

**Comment by lbialy** [comment]
This won't really change much with the small difference that you will get a Validated with NonEmptyVector of errors instead of Either.

**Comment by lbialy** [comment]
@KacperFKorban FYI

**Comment by lbialy** [comment]
Still requires @KacperFKorban changes.

**Comment by pawelprazak** [comment]
I'm guessing those are the referred changes: https://github.com/VirtusLab/besom/pull/173/files

**Comment by pawelprazak** [comment]
rebased, tests green @lbialy

**Review by lbialy — APPROVED** [review]

**Pull request merged**
