### PR TITLE
Allow val defined as a const to be used as NES

### PR DESCRIPTION
**Pull request by Kordyjan**
This change allows references to values defined as non-empty constants to be used as NonEmptyStrings.
Works when the `-Yretain-trees` flag is enabled.

It can be taken further by applying the checks recursively, e.g., we can check make things like 

```scala
val x = s"abc${"xyz"}"
val nes: NonEmptyString = x
```

or 

```scala
val x = "ABC"
val y = "def"
val nes: NonEmptyString = s"$x$y"
```

work.

### CODE REVIEW

**Comment by lbialy** [comment]
@prolativ can you please add -YretainTrees to default setup of Scala-cli launcher, templates and a test?

**Comment by prolativ** [comment]
@lbialy is this something we need for our initial release? I would opt for holding this a bit to do some experiments and see how this pattern might influence users' code

**Comment by lbialy** [comment]
Ok, sure.

**Comment by lbialy** [comment]
This is subsumed by #375. Thank you @Kordyjan for all the help with this!

**Pull request closed without merging**
