### PR TITLE
WIP Fixed the log file naming problem for CI

### PR DESCRIPTION
**Pull request by lbialy**

### CODE REVIEW

**Review by pawelprazak — APPROVED** [review]

**Comment by lbialy** [comment]
DO NOT UNDER ANY CONDITION MERGE THIS

**Comment by pawelprazak** [comment]
it kinda make sense thou ;)

**Comment by lbialy** [comment]
yeah, we could have that flag for CI debug but it's my dirty branch and I wish to work on it to fix the deadlock

**Comment by pawelprazak** [comment]
your dirty branch looks very clean to me 😀 

anyway, carry on :)

**Comment by pawelprazak** [comment]
I think we can close this since #202 addressed the issue

**Review by pawelprazak — CHANGES_REQUESTED** [review]
reverting approve

**Comment by lbialy** [comment]
I think this can be closed safely now @pawelprazak You made that change in a separate PR, right?

**Pull request closed without merging**
