### PR TITLE
add aws eks hello world example

### PR DESCRIPTION
**Pull request by polkx**

### CODE REVIEW

**Comment by pawelprazak** [comment]
Thank you. What is new vs. https://github.com/VirtusLab/besom/blob/main/examples/aws-eks/Main.scala ?

**Comment by polkx** [comment]
> Thank you. What is new vs. https://github.com/VirtusLab/besom/blob/main/examples/aws-eks/Main.scala ?

In this example, I added the ability to see running application on a browser.

**Comment by pawelprazak** [comment]
Could you incorporate this feature into existing example?

**Review by pawelprazak — APPROVED** [review]
LGTM, thank you. I've resolved the conflict in `project.scala`

**Pull request merged**
